[workspace]
members = [
  "controller",
  "client-tracking",
  "shared-types",
]
default-members = [
  "controller",
  "client-tracking",
  "shared-types",
]

resolver = "2"


[workspace.package]
edition = "2021"
rust-version = "1.73"
