use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Serialize, Deserialize, Eq, PartialOrd, Clone, Copy)]
pub enum YoloClasses80 {
    Person,
    Bicycle,
    Car,
    Motorcycle,
    Airplane,
    Bus,
    Train,
    Truck,
    Boat,
    TrafficLight,
    FireHydrant,
    StopSign,
    ParkingMeter,
    Bench,
    Bird,
    Cat,
    Dog,
    Horse,
    Sheep,
    Cow,
    Elephant,
    Bear,
    Zebra,
    Giraffe,
    Backpack,
    Umbrella,
    Handbag,
    Tie,
    Suitcase,
    Frisbee,
    Skis,
    Snowboard,
    SportsBall,
    Kite,
    BaseballBat,
    BaseballGlove,
    Skateboard,
    Surfboard,
    TennisRacket,
    Bottle,
    WineGlass,
    Cup,
    Fork,
    Knife,
    Spoon,
    Bowl,
    Banana,
    Apple,
    Sandwich,
    Orange,
    Broccoli,
    Carrot,
    HotDog,
    Pizza,
    Donut,
    Cake,
    Chair,
    Couch,
    PottedPlant,
    Bed,
    DiningTable,
    Toilet,
    Tv,
    Laptop,
    Mouse,
    Remote,
    Keyboard,
    CellPhone,
    Microwave,
    Oven,
    Toaster,
    Sink,
    Refrigerator,
    Book,
    Clock,
    Vase,
    Scissors,
    TeddyBear,
    HairDrier,
    Toothbrush,
}

impl From<usize> for YoloClasses80 {
    fn from(label: usize) -> Self {
        match label {
            0 => YoloClasses80::Person,
            1 => YoloClasses80::Bicycle,
            2 => YoloClasses80::Car,
            3 => YoloClasses80::Motorcycle,
            4 => YoloClasses80::Airplane,
            5 => YoloClasses80::Bus,
            6 => YoloClasses80::Train,
            7 => YoloClasses80::Truck,
            8 => YoloClasses80::Boat,
            9 => YoloClasses80::TrafficLight,
            10 => YoloClasses80::FireHydrant,
            11 => YoloClasses80::StopSign,
            12 => YoloClasses80::ParkingMeter,
            13 => YoloClasses80::Bench,
            14 => YoloClasses80::Bird,
            15 => YoloClasses80::Cat,
            16 => YoloClasses80::Dog,
            17 => YoloClasses80::Horse,
            18 => YoloClasses80::Sheep,
            19 => YoloClasses80::Cow,
            20 => YoloClasses80::Elephant,
            21 => YoloClasses80::Bear,
            22 => YoloClasses80::Zebra,
            23 => YoloClasses80::Giraffe,
            24 => YoloClasses80::Backpack,
            25 => YoloClasses80::Umbrella,
            26 => YoloClasses80::Handbag,
            27 => YoloClasses80::Tie,
            28 => YoloClasses80::Suitcase,
            29 => YoloClasses80::Frisbee,
            30 => YoloClasses80::Skis,
            31 => YoloClasses80::Snowboard,
            32 => YoloClasses80::SportsBall,
            33 => YoloClasses80::Kite,
            34 => YoloClasses80::BaseballBat,
            35 => YoloClasses80::BaseballGlove,
            36 => YoloClasses80::Skateboard,
            37 => YoloClasses80::Surfboard,
            38 => YoloClasses80::TennisRacket,
            39 => YoloClasses80::Bottle,
            40 => YoloClasses80::WineGlass,
            41 => YoloClasses80::Cup,
            42 => YoloClasses80::Fork,
            43 => YoloClasses80::Knife,
            44 => YoloClasses80::Spoon,
            45 => YoloClasses80::Bowl,
            46 => YoloClasses80::Banana,
            47 => YoloClasses80::Apple,
            48 => YoloClasses80::Sandwich,
            49 => YoloClasses80::Orange,
            50 => YoloClasses80::Broccoli,
            51 => YoloClasses80::Carrot,
            52 => YoloClasses80::HotDog,
            53 => YoloClasses80::Pizza,
            54 => YoloClasses80::Donut,
            55 => YoloClasses80::Cake,
            56 => YoloClasses80::Chair,
            57 => YoloClasses80::Couch,
            58 => YoloClasses80::PottedPlant,
            59 => YoloClasses80::Bed,
            60 => YoloClasses80::DiningTable,
            61 => YoloClasses80::Toilet,
            62 => YoloClasses80::Tv,
            63 => YoloClasses80::Laptop,
            64 => YoloClasses80::Mouse,
            65 => YoloClasses80::Remote,
            66 => YoloClasses80::Keyboard,
            67 => YoloClasses80::CellPhone,
            68 => YoloClasses80::Microwave,
            69 => YoloClasses80::Oven,
            70 => YoloClasses80::Toaster,
            71 => YoloClasses80::Sink,
            72 => YoloClasses80::Refrigerator,
            73 => YoloClasses80::Book,
            74 => YoloClasses80::Clock,
            75 => YoloClasses80::Vase,
            76 => YoloClasses80::Scissors,
            77 => YoloClasses80::TeddyBear,
            78 => YoloClasses80::HairDrier,
            79 => YoloClasses80::Toothbrush,
            _ => panic!("The Label returned a bigger number than what was expected"),
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize, Eq, PartialOrd, Clone, Copy)]
pub enum YoloClassesOIV7 {
    Accordion,
    AdhesiveTape,
    Aircraft,
    Airplane,
    AlarmClock,
    Alpaca,
    Ambulance,
    Animal,
    Ant,
    Antelope,
    Apple,
    Armadillo,
    Artichoke,
    AutoPart,
    Axe,
    Backpack,
    Bagel,
    BakedGoods,
    BalanceBeam,
    Ball,
    Balloon,
    Banana,
    BandAid,
    Banjo,
    Barge,
    Barrel,
    BaseballBat,
    BaseballGlove,
    Bat, // (Animal)
    BathroomAccessory,
    BathroomCabinet,
    Bathtub,
    Beaker,
    Bear,
    Bed,
    Bee,
    Beehive,
    Beer,
    Beetle,
    BellPepper,
    Belt,
    Bench,
    Bicycle,
    BicycleHelmet,
    BicycleWheel,
    Bidet,
    Billboard,
    BilliardTable,
    Binoculars,
    Bird,
    Blender,
    BlueJay,
    Boat,
    Bomb,
    Book,
    Bookcase,
    Boot,
    Bottle,
    BottleOpener,
    BowAndArrow,
    Bowl,
    BowlingEquipment,
    Box,
    Boy,
    Brassiere,
    Bread,
    Briefcase,
    Broccoli,
    BronzeSculpture,
    BrownBear,
    Building,
    Bull,
    Burrito,
    Bus,
    Bust,
    Butterfly,
    Cabbage,
    Cabinetry,
    Cake,
    CakeStand,
    Calculator,
    Camel,
    Camera,
    CanOpener,
    Canary,
    Candle,
    Candy,
    Cannon,
    Canoe,
    Cantaloupe,
    Car,
    Carnivore,
    Carrot,
    Cart,
    CassetteDeck,
    Castle,
    Cat,
    CatFurniture,
    Caterpillar,
    Cattle,
    CeilingFan,
    Cello,
    Centipede,
    Chainsaw,
    Chair,
    Cheese,
    Cheetah,
    ChestOfDrawers,
    Chicken,
    Chime,
    Chisel,
    Chopsticks,
    ChristmasTree,
    Clock,
    Closet,
    Clothing,
    Coat,
    Cocktail,
    CocktailShaker,
    Coconut,
    Coffee,
    CoffeeCup,
    CoffeeTable,
    Coffeemaker,
    Coin,
    CommonFig,
    CommonSunflower,
    ComputerKeyboard,
    ComputerMonitor,
    ComputerMouse,
    Container,
    ConvenienceStore,
    Cookie,
    CookingSpray,
    CordedPhone,
    Cosmetics,
    Couch,
    Countertop,
    CowboyHat,
    Crab,
    Cream,
    CricketBall,
    Crocodile,
    Croissant,
    Crown,
    Crutch,
    Cucumber,
    Cupboard,
    Curtain,
    CuttingBoard,
    Dagger,
    DairyProduct,
    Deer,
    Desk,
    Dessert,
    Diaper,
    Dice,
    DigitalClock,
    Dinosaur,
    Dishwasher,
    Dog,
    DogBed,
    Doll,
    Dolphin,
    Door,
    DoorHandle,
    Doughnut,
    Dragonfly,
    Drawer,
    Dress,
    Drill, // (Tool)
    Drink,
    DrinkingStraw,
    Drum,
    Duck,
    Dumbbell,
    Eagle,
    Earrings,
    Egg, //  (Food)
    Elephant,
    Envelope,
    Eraser,
    FacePowder,
    FacialTissueHolder,
    Falcon,
    FashionAccessory,
    FastFood,
    Fax,
    Fedora,
    FilingCabinet,
    FireHydrant,
    Fireplace,
    Fish,
    Flag,
    Flashlight,
    Flower,
    Flowerpot,
    Flute,
    FlyingDisc,
    Food,
    FoodProcessor,
    Football,
    FootballHelmet,
    Footwear,
    Fork,
    Fountain,
    Fox,
    FrenchFries,
    FrenchHorn,
    Frog,
    Fruit,
    FryingPan,
    Furniture,
    GardenAsparagus,
    GasStove,
    Giraffe,
    Girl,
    Glasses,
    Glove,
    Goat,
    Goggles,
    Goldfish,
    GolfBall,
    GolfCart,
    Gondola,
    Goose,
    Grape,
    Grapefruit,
    Grinder,
    Guacamole,
    Guitar,
    HairDryer,
    HairSpray,
    Hamburger,
    Hammer,
    Hamster,
    HandDryer,
    Handbag,
    Handgun,
    HarborSeal,
    Harmonica,
    Harp,
    Harpsichord,
    Hat,
    Headphones,
    Heater,
    Hedgehog,
    Helicopter,
    Helmet,
    HighHeels,
    HikingEquipment,
    Hippopotamus,
    HomeAppliance,
    Honeycomb,
    HorizontalBar,
    Horse,
    HotDog,
    House,
    Houseplant,
    HumanArm,
    HumanBeard,
    HumanBody,
    HumanEar,
    HumanEye,
    HumanFace,
    HumanFoot,
    HumanHair,
    HumanHand,
    HumanHead,
    HumanLeg,
    HumanMouth,
    HumanNose,
    Humidifier,
    IceCream,
    IndoorRower,
    InfantBed,
    Insect,
    Invertebrate,
    Ipod,
    Isopod,
    Jacket,
    Jacuzzi,
    Jaguar, // (Animal)
    Jeans,
    Jellyfish,
    JetSki,
    Jug,
    Juice,
    Kangaroo,
    Kettle,
    DinnerTable,
    KitchenAppliance,
    KitchenKnife,
    KitchenUtensil,
    Kitchenware,
    Kite,
    Knife,
    Koala,
    Ladder,
    Ladle,
    Ladybug,
    Lamp,
    LandVehicle,
    Lantern,
    Laptop,
    Lavender, // (Plant)
    Lemon,
    Leopard,
    LightBulb,
    LightSwitch,
    Lighthouse,
    Lily,
    Limousine,
    Lion,
    Lipstick,
    Lizard,
    Lobster,
    Loveseat,
    LuggageAndBags,
    Lynx,
    Magpie,
    Mammal,
    Man,
    Mango,
    Maple,
    Maracas,
    MarineInvertebrates,
    MarineMammal,
    MeasuringCup,
    MechanicalFan,
    MedicalEquipment,
    Microphone,
    MicrowaveOven,
    Milk,
    Miniskirt,
    Mirror,
    Missile,
    Mixer,
    MixingBowl,
    MobilePhone,
    Monkey,
    MothsAndButterflies,
    Motorcycle,
    Mouse,
    Muffin,
    Mug,
    Mule,
    Mushroom,
    MusicalInstrument,
    MusicalKeyboard,
    Nail, // (Construction)
    Necklace,
    Nightstand,
    Oboe,
    OfficeBuilding,
    OfficeSupplies,
    Orange,
    Organ, // (Musical Instrument)
    Ostrich,
    Otter,
    Oven,
    Owl,
    Oyster,
    Paddle,
    PalmTree,
    Pancake,
    Panda,
    PaperCutter,
    PaperTowel,
    Parachute,
    ParkingMeter,
    Parrot,
    Pasta,
    Pastry,
    Peach,
    Pear,
    Pen,
    PencilCase,
    PencilSharpener,
    Penguin,
    Perfume,
    Person,
    PersonalCare,
    PersonalFlotationDevice,
    Piano,
    PicnicBasket,
    PictureFrame,
    Pig,
    Pillow,
    Pineapple,
    Pitcher, // (Container)
    Pizza,
    PizzaCutter,
    Plant,
    PlasticBag,
    Plate,
    Platter,
    PlumbingFixture,
    PolarBear,
    Pomegranate,
    Popcorn,
    Porch,
    Porcupine,
    Poster,
    Potato,
    PowerPlugsAndSockets,
    PressureCooker,
    Pretzel,
    Printer,
    Pumpkin,
    PunchingBag,
    Rabbit,
    Raccoon,
    Racket,
    Radish,
    Ratchet, // (Device)
    Raven,
    RaysAndSkates,
    RedPanda,
    Refrigerator,
    RemoteControl,
    Reptile,
    Rhinoceros,
    Rifle,
    RingBinder,
    Rocket,
    RollerSkates,
    Rose,
    RugbyBall,
    Ruler,
    Salad,
    SaltAndPepperShakers,
    Sandal,
    Sandwich,
    Saucer,
    Saxophone,
    Scale,
    Scarf,
    Scissors,
    Scoreboard,
    Scorpion,
    Screwdriver,
    Sculpture,
    SeaLion,
    SeaTurtle,
    Seafood,
    Seahorse,
    SeatBelt,
    Segway,
    ServingTray,
    SewingMachine,
    Shark,
    Sheep,
    Shelf,
    Shellfish,
    Shirt,
    Shorts,
    Shotgun,
    Shower,
    Shrimp,
    Sink,
    Skateboard,
    Ski,
    Skirt,
    Skull,
    Skunk,
    Skyscraper,
    SlowCooker,
    Snack,
    Snail,
    Snake,
    Snowboard,
    Snowman,
    Snowmobile,
    Snowplow,
    SoapDispenser,
    Sock,
    SofaBed,
    Sombrero,
    Sparrow,
    Spatula,
    SpiceRack,
    Spider,
    Spoon,
    SportsEquipment,
    SportsUniform,
    Squash, //(Plant)
    Squid,
    Squirrel,
    Stairs,
    Stapler,
    Starfish,
    StationaryBicycle,
    Stethoscope,
    Stool,
    StopSign,
    Strawberry,
    StreetLight,
    Stretcher,
    StudioCouch,
    Submarine,
    SubmarineSandwich,
    Suit,
    Suitcase,
    SunHat,
    Sunglasses,
    Surfboard,
    Sushi,
    Swan,
    SwimCap,
    SwimmingPool,
    Swimwear,
    Sword,
    Syringe,
    Table,
    TableTennisRacket,
    TabletComputer,
    Tableware,
    Taco,
    Tank,
    Tap,
    Tart,
    Taxi,
    Tea,
    Teapot,
    TeddyBear,
    Telephone,
    Television,
    TennisBall,
    TennisRacket,
    Tent,
    Tiara,
    Tick,
    Tie,
    Tiger,
    TinCan,
    Tire,
    Toaster,
    Toilet,
    ToiletPaper,
    Tomato,
    Tool,
    Toothbrush,
    Torch,
    Tortoise,
    Towel,
    Tower,
    Toy,
    TrafficLight,
    TrafficSign,
    Train,
    TrainingBench,
    Treadmill,
    Tree,
    TreeHouse,
    Tripod,
    Trombone,
    Trousers,
    Truck,
    Trumpet,
    Turkey,
    Turtle,
    Umbrella,
    Unicycle,
    Van,
    Vase,
    Vegetable,
    Vehicle,
    VehicleRegistrationPlate,
    Violin,
    Volleyball, // (Ball)
    Waffle,
    WaffleIron,
    WallClock,
    Wardrobe,
    WashingMachine,
    WasteContainer,
    Watch,
    Watercraft,
    Watermelon,
    Weapon,
    Whale,
    Wheel,
    Wheelchair,
    Whisk,
    Whiteboard,
    Willow,
    Window,
    WindowBlind,
    Wine,
    WineGlass,
    WineRack,
    WinterMelon,
    Wok,
    Woman,
    WoodBurningStove,
    Woodpecker,
    Worm,
    Wrench,
    Zebra,
    Zucchini,
}

impl From<usize> for YoloClassesOIV7 {
    fn from(label: usize) -> YoloClassesOIV7 {
        match label {
            0 => YoloClassesOIV7::Accordion,
            1 => YoloClassesOIV7::AdhesiveTape,
            2 => YoloClassesOIV7::Aircraft,
            3 => YoloClassesOIV7::Airplane,
            4 => YoloClassesOIV7::AlarmClock,
            5 => YoloClassesOIV7::Alpaca,
            6 => YoloClassesOIV7::Ambulance,
            7 => YoloClassesOIV7::Animal,
            8 => YoloClassesOIV7::Ant,
            9 => YoloClassesOIV7::Antelope,
            10 => YoloClassesOIV7::Apple,
            11 => YoloClassesOIV7::Armadillo,
            12 => YoloClassesOIV7::Artichoke,
            13 => YoloClassesOIV7::AutoPart,
            14 => YoloClassesOIV7::Axe,
            15 => YoloClassesOIV7::Backpack,
            16 => YoloClassesOIV7::Bagel,
            17 => YoloClassesOIV7::BakedGoods,
            18 => YoloClassesOIV7::BalanceBeam,
            19 => YoloClassesOIV7::Ball,
            20 => YoloClassesOIV7::Balloon,
            21 => YoloClassesOIV7::Banana,
            22 => YoloClassesOIV7::BandAid,
            23 => YoloClassesOIV7::Banjo,
            24 => YoloClassesOIV7::Barge,
            25 => YoloClassesOIV7::Barrel,
            26 => YoloClassesOIV7::BaseballBat,
            27 => YoloClassesOIV7::BaseballGlove,
            28 => YoloClassesOIV7::Bat, // (Animal)
            29 => YoloClassesOIV7::BathroomAccessory,
            30 => YoloClassesOIV7::BathroomCabinet,
            31 => YoloClassesOIV7::Bathtub,
            32 => YoloClassesOIV7::Beaker,
            33 => YoloClassesOIV7::Bear,
            34 => YoloClassesOIV7::Bed,
            35 => YoloClassesOIV7::Bee,
            36 => YoloClassesOIV7::Beehive,
            37 => YoloClassesOIV7::Beer,
            38 => YoloClassesOIV7::Beetle,
            39 => YoloClassesOIV7::BellPepper,
            40 => YoloClassesOIV7::Belt,
            41 => YoloClassesOIV7::Bench,
            42 => YoloClassesOIV7::Bicycle,
            43 => YoloClassesOIV7::BicycleHelmet,
            44 => YoloClassesOIV7::BicycleWheel,
            45 => YoloClassesOIV7::Bidet,
            46 => YoloClassesOIV7::Billboard,
            47 => YoloClassesOIV7::BilliardTable,
            48 => YoloClassesOIV7::Binoculars,
            49 => YoloClassesOIV7::Bird,
            50 => YoloClassesOIV7::Blender,
            51 => YoloClassesOIV7::BlueJay,
            52 => YoloClassesOIV7::Boat,
            53 => YoloClassesOIV7::Bomb,
            54 => YoloClassesOIV7::Book,
            55 => YoloClassesOIV7::Bookcase,
            56 => YoloClassesOIV7::Boot,
            57 => YoloClassesOIV7::Bottle,
            58 => YoloClassesOIV7::BottleOpener,
            59 => YoloClassesOIV7::BowAndArrow,
            60 => YoloClassesOIV7::Bowl,
            61 => YoloClassesOIV7::BowlingEquipment,
            62 => YoloClassesOIV7::Box,
            63 => YoloClassesOIV7::Boy,
            64 => YoloClassesOIV7::Brassiere,
            65 => YoloClassesOIV7::Bread,
            66 => YoloClassesOIV7::Briefcase,
            67 => YoloClassesOIV7::Broccoli,
            68 => YoloClassesOIV7::BronzeSculpture,
            69 => YoloClassesOIV7::BrownBear,
            70 => YoloClassesOIV7::Building,
            71 => YoloClassesOIV7::Bull,
            72 => YoloClassesOIV7::Burrito,
            73 => YoloClassesOIV7::Bus,
            74 => YoloClassesOIV7::Bust,
            75 => YoloClassesOIV7::Butterfly,
            76 => YoloClassesOIV7::Cabbage,
            77 => YoloClassesOIV7::Cabinetry,
            78 => YoloClassesOIV7::Cake,
            79 => YoloClassesOIV7::CakeStand,
            80 => YoloClassesOIV7::Calculator,
            81 => YoloClassesOIV7::Camel,
            82 => YoloClassesOIV7::Camera,
            83 => YoloClassesOIV7::CanOpener,
            84 => YoloClassesOIV7::Canary,
            85 => YoloClassesOIV7::Candle,
            86 => YoloClassesOIV7::Candy,
            87 => YoloClassesOIV7::Cannon,
            88 => YoloClassesOIV7::Canoe,
            89 => YoloClassesOIV7::Cantaloupe,
            90 => YoloClassesOIV7::Car,
            91 => YoloClassesOIV7::Carnivore,
            92 => YoloClassesOIV7::Carrot,
            93 => YoloClassesOIV7::Cart,
            94 => YoloClassesOIV7::CassetteDeck,
            95 => YoloClassesOIV7::Castle,
            96 => YoloClassesOIV7::Cat,
            97 => YoloClassesOIV7::CatFurniture,
            98 => YoloClassesOIV7::Caterpillar,
            99 => YoloClassesOIV7::Cattle,
            100 => YoloClassesOIV7::CeilingFan,
            101 => YoloClassesOIV7::Cello,
            102 => YoloClassesOIV7::Centipede,
            103 => YoloClassesOIV7::Chainsaw,
            104 => YoloClassesOIV7::Chair,
            105 => YoloClassesOIV7::Cheese,
            106 => YoloClassesOIV7::Cheetah,
            107 => YoloClassesOIV7::ChestOfDrawers,
            108 => YoloClassesOIV7::Chicken,
            109 => YoloClassesOIV7::Chime,
            110 => YoloClassesOIV7::Chisel,
            111 => YoloClassesOIV7::Chopsticks,
            112 => YoloClassesOIV7::ChristmasTree,
            113 => YoloClassesOIV7::Clock,
            114 => YoloClassesOIV7::Closet,
            115 => YoloClassesOIV7::Clothing,
            116 => YoloClassesOIV7::Coat,
            117 => YoloClassesOIV7::Cocktail,
            118 => YoloClassesOIV7::CocktailShaker,
            119 => YoloClassesOIV7::Coconut,
            120 => YoloClassesOIV7::Coffee,
            121 => YoloClassesOIV7::CoffeeCup,
            122 => YoloClassesOIV7::CoffeeTable,
            123 => YoloClassesOIV7::Coffeemaker,
            124 => YoloClassesOIV7::Coin,
            125 => YoloClassesOIV7::CommonFig,
            126 => YoloClassesOIV7::CommonSunflower,
            127 => YoloClassesOIV7::ComputerKeyboard,
            128 => YoloClassesOIV7::ComputerMonitor,
            129 => YoloClassesOIV7::ComputerMouse,
            130 => YoloClassesOIV7::Container,
            131 => YoloClassesOIV7::ConvenienceStore,
            132 => YoloClassesOIV7::Cookie,
            133 => YoloClassesOIV7::CookingSpray,
            134 => YoloClassesOIV7::CordedPhone,
            135 => YoloClassesOIV7::Cosmetics,
            136 => YoloClassesOIV7::Couch,
            137 => YoloClassesOIV7::Countertop,
            138 => YoloClassesOIV7::CowboyHat,
            139 => YoloClassesOIV7::Crab,
            140 => YoloClassesOIV7::Cream,
            141 => YoloClassesOIV7::CricketBall,
            142 => YoloClassesOIV7::Crocodile,
            143 => YoloClassesOIV7::Croissant,
            144 => YoloClassesOIV7::Crown,
            145 => YoloClassesOIV7::Crutch,
            146 => YoloClassesOIV7::Cucumber,
            147 => YoloClassesOIV7::Cupboard,
            148 => YoloClassesOIV7::Curtain,
            149 => YoloClassesOIV7::CuttingBoard,
            150 => YoloClassesOIV7::Dagger,
            151 => YoloClassesOIV7::DairyProduct,
            152 => YoloClassesOIV7::Deer,
            153 => YoloClassesOIV7::Desk,
            154 => YoloClassesOIV7::Dessert,
            155 => YoloClassesOIV7::Diaper,
            156 => YoloClassesOIV7::Dice,
            157 => YoloClassesOIV7::DigitalClock,
            158 => YoloClassesOIV7::Dinosaur,
            159 => YoloClassesOIV7::Dishwasher,
            160 => YoloClassesOIV7::Dog,
            161 => YoloClassesOIV7::DogBed,
            162 => YoloClassesOIV7::Doll,
            163 => YoloClassesOIV7::Dolphin,
            164 => YoloClassesOIV7::Door,
            165 => YoloClassesOIV7::DoorHandle,
            166 => YoloClassesOIV7::Doughnut,
            167 => YoloClassesOIV7::Dragonfly,
            168 => YoloClassesOIV7::Drawer,
            169 => YoloClassesOIV7::Dress,
            170 => YoloClassesOIV7::Drill, // (Tool)
            171 => YoloClassesOIV7::Drink,
            172 => YoloClassesOIV7::DrinkingStraw,
            173 => YoloClassesOIV7::Drum,
            174 => YoloClassesOIV7::Duck,
            175 => YoloClassesOIV7::Dumbbell,
            176 => YoloClassesOIV7::Eagle,
            177 => YoloClassesOIV7::Earrings,
            178 => YoloClassesOIV7::Egg, //  (Food)
            179 => YoloClassesOIV7::Elephant,
            180 => YoloClassesOIV7::Envelope,
            181 => YoloClassesOIV7::Eraser,
            182 => YoloClassesOIV7::FacePowder,
            183 => YoloClassesOIV7::FacialTissueHolder,
            184 => YoloClassesOIV7::Falcon,
            185 => YoloClassesOIV7::FashionAccessory,
            186 => YoloClassesOIV7::FastFood,
            187 => YoloClassesOIV7::Fax,
            188 => YoloClassesOIV7::Fedora,
            189 => YoloClassesOIV7::FilingCabinet,
            190 => YoloClassesOIV7::FireHydrant,
            191 => YoloClassesOIV7::Fireplace,
            192 => YoloClassesOIV7::Fish,
            193 => YoloClassesOIV7::Flag,
            194 => YoloClassesOIV7::Flashlight,
            195 => YoloClassesOIV7::Flower,
            196 => YoloClassesOIV7::Flowerpot,
            197 => YoloClassesOIV7::Flute,
            198 => YoloClassesOIV7::FlyingDisc,
            199 => YoloClassesOIV7::Food,
            200 => YoloClassesOIV7::FoodProcessor,
            201 => YoloClassesOIV7::Football,
            202 => YoloClassesOIV7::FootballHelmet,
            203 => YoloClassesOIV7::Footwear,
            204 => YoloClassesOIV7::Fork,
            205 => YoloClassesOIV7::Fountain,
            206 => YoloClassesOIV7::Fox,
            207 => YoloClassesOIV7::FrenchFries,
            208 => YoloClassesOIV7::FrenchHorn,
            209 => YoloClassesOIV7::Frog,
            210 => YoloClassesOIV7::Fruit,
            211 => YoloClassesOIV7::FryingPan,
            212 => YoloClassesOIV7::Furniture,
            213 => YoloClassesOIV7::GardenAsparagus,
            214 => YoloClassesOIV7::GasStove,
            215 => YoloClassesOIV7::Giraffe,
            216 => YoloClassesOIV7::Girl,
            217 => YoloClassesOIV7::Glasses,
            218 => YoloClassesOIV7::Glove,
            219 => YoloClassesOIV7::Goat,
            220 => YoloClassesOIV7::Goggles,
            221 => YoloClassesOIV7::Goldfish,
            222 => YoloClassesOIV7::GolfBall,
            223 => YoloClassesOIV7::GolfCart,
            224 => YoloClassesOIV7::Gondola,
            225 => YoloClassesOIV7::Goose,
            226 => YoloClassesOIV7::Grape,
            227 => YoloClassesOIV7::Grapefruit,
            228 => YoloClassesOIV7::Grinder,
            229 => YoloClassesOIV7::Guacamole,
            230 => YoloClassesOIV7::Guitar,
            231 => YoloClassesOIV7::HairDryer,
            232 => YoloClassesOIV7::HairSpray,
            233 => YoloClassesOIV7::Hamburger,
            234 => YoloClassesOIV7::Hammer,
            235 => YoloClassesOIV7::Hamster,
            236 => YoloClassesOIV7::HandDryer,
            237 => YoloClassesOIV7::Handbag,
            238 => YoloClassesOIV7::Handgun,
            239 => YoloClassesOIV7::HarborSeal,
            240 => YoloClassesOIV7::Harmonica,
            241 => YoloClassesOIV7::Harp,
            242 => YoloClassesOIV7::Harpsichord,
            243 => YoloClassesOIV7::Hat,
            244 => YoloClassesOIV7::Headphones,
            245 => YoloClassesOIV7::Heater,
            246 => YoloClassesOIV7::Hedgehog,
            247 => YoloClassesOIV7::Helicopter,
            248 => YoloClassesOIV7::Helmet,
            249 => YoloClassesOIV7::HighHeels,
            250 => YoloClassesOIV7::HikingEquipment,
            251 => YoloClassesOIV7::Hippopotamus,
            252 => YoloClassesOIV7::HomeAppliance,
            253 => YoloClassesOIV7::Honeycomb,
            254 => YoloClassesOIV7::HorizontalBar,
            255 => YoloClassesOIV7::Horse,
            256 => YoloClassesOIV7::HotDog,
            257 => YoloClassesOIV7::House,
            258 => YoloClassesOIV7::Houseplant,
            259 => YoloClassesOIV7::HumanArm,
            260 => YoloClassesOIV7::HumanBeard,
            261 => YoloClassesOIV7::HumanBody,
            262 => YoloClassesOIV7::HumanEar,
            263 => YoloClassesOIV7::HumanEye,
            264 => YoloClassesOIV7::HumanFace,
            265 => YoloClassesOIV7::HumanFoot,
            266 => YoloClassesOIV7::HumanHair,
            267 => YoloClassesOIV7::HumanHand,
            268 => YoloClassesOIV7::HumanHead,
            269 => YoloClassesOIV7::HumanLeg,
            270 => YoloClassesOIV7::HumanMouth,
            271 => YoloClassesOIV7::HumanNose,
            272 => YoloClassesOIV7::Humidifier,
            273 => YoloClassesOIV7::IceCream,
            274 => YoloClassesOIV7::IndoorRower,
            275 => YoloClassesOIV7::InfantBed,
            276 => YoloClassesOIV7::Insect,
            277 => YoloClassesOIV7::Invertebrate,
            278 => YoloClassesOIV7::Ipod,
            279 => YoloClassesOIV7::Isopod,
            280 => YoloClassesOIV7::Jacket,
            281 => YoloClassesOIV7::Jacuzzi,
            282 => YoloClassesOIV7::Jaguar, // (Animal)
            283 => YoloClassesOIV7::Jeans,
            284 => YoloClassesOIV7::Jellyfish,
            285 => YoloClassesOIV7::JetSki,
            286 => YoloClassesOIV7::Jug,
            287 => YoloClassesOIV7::Juice,
            288 => YoloClassesOIV7::Kangaroo,
            289 => YoloClassesOIV7::Kettle,
            290 => YoloClassesOIV7::DinnerTable,
            291 => YoloClassesOIV7::KitchenAppliance,
            292 => YoloClassesOIV7::KitchenKnife,
            293 => YoloClassesOIV7::KitchenUtensil,
            294 => YoloClassesOIV7::Kitchenware,
            295 => YoloClassesOIV7::Kite,
            296 => YoloClassesOIV7::Knife,
            297 => YoloClassesOIV7::Koala,
            298 => YoloClassesOIV7::Ladder,
            299 => YoloClassesOIV7::Ladle,
            300 => YoloClassesOIV7::Ladybug,
            301 => YoloClassesOIV7::Lamp,
            302 => YoloClassesOIV7::LandVehicle,
            303 => YoloClassesOIV7::Lantern,
            304 => YoloClassesOIV7::Laptop,
            305 => YoloClassesOIV7::Lavender, // (Plant)
            306 => YoloClassesOIV7::Lemon,
            307 => YoloClassesOIV7::Leopard,
            308 => YoloClassesOIV7::LightBulb,
            309 => YoloClassesOIV7::LightSwitch,
            310 => YoloClassesOIV7::Lighthouse,
            311 => YoloClassesOIV7::Lily,
            312 => YoloClassesOIV7::Limousine,
            313 => YoloClassesOIV7::Lion,
            314 => YoloClassesOIV7::Lipstick,
            315 => YoloClassesOIV7::Lizard,
            316 => YoloClassesOIV7::Lobster,
            317 => YoloClassesOIV7::Loveseat,
            318 => YoloClassesOIV7::LuggageAndBags,
            319 => YoloClassesOIV7::Lynx,
            320 => YoloClassesOIV7::Magpie,
            321 => YoloClassesOIV7::Mammal,
            322 => YoloClassesOIV7::Man,
            323 => YoloClassesOIV7::Mango,
            324 => YoloClassesOIV7::Maple,
            325 => YoloClassesOIV7::Maracas,
            326 => YoloClassesOIV7::MarineInvertebrates,
            327 => YoloClassesOIV7::MarineMammal,
            328 => YoloClassesOIV7::MeasuringCup,
            329 => YoloClassesOIV7::MechanicalFan,
            330 => YoloClassesOIV7::MedicalEquipment,
            331 => YoloClassesOIV7::Microphone,
            332 => YoloClassesOIV7::MicrowaveOven,
            333 => YoloClassesOIV7::Milk,
            334 => YoloClassesOIV7::Miniskirt,
            335 => YoloClassesOIV7::Mirror,
            336 => YoloClassesOIV7::Missile,
            337 => YoloClassesOIV7::Mixer,
            338 => YoloClassesOIV7::MixingBowl,
            339 => YoloClassesOIV7::MobilePhone,
            340 => YoloClassesOIV7::Monkey,
            341 => YoloClassesOIV7::MothsAndButterflies,
            342 => YoloClassesOIV7::Motorcycle,
            343 => YoloClassesOIV7::Mouse,
            344 => YoloClassesOIV7::Muffin,
            345 => YoloClassesOIV7::Mug,
            346 => YoloClassesOIV7::Mule,
            347 => YoloClassesOIV7::Mushroom,
            348 => YoloClassesOIV7::MusicalInstrument,
            349 => YoloClassesOIV7::MusicalKeyboard,
            350 => YoloClassesOIV7::Nail, // (Construction)
            351 => YoloClassesOIV7::Necklace,
            352 => YoloClassesOIV7::Nightstand,
            353 => YoloClassesOIV7::Oboe,
            354 => YoloClassesOIV7::OfficeBuilding,
            355 => YoloClassesOIV7::OfficeSupplies,
            356 => YoloClassesOIV7::Orange,
            357 => YoloClassesOIV7::Organ, // (Musical Instrument)
            358 => YoloClassesOIV7::Ostrich,
            359 => YoloClassesOIV7::Otter,
            360 => YoloClassesOIV7::Oven,
            361 => YoloClassesOIV7::Owl,
            362 => YoloClassesOIV7::Oyster,
            363 => YoloClassesOIV7::Paddle,
            364 => YoloClassesOIV7::PalmTree,
            365 => YoloClassesOIV7::Pancake,
            366 => YoloClassesOIV7::Panda,
            367 => YoloClassesOIV7::PaperCutter,
            368 => YoloClassesOIV7::PaperTowel,
            369 => YoloClassesOIV7::Parachute,
            370 => YoloClassesOIV7::ParkingMeter,
            371 => YoloClassesOIV7::Parrot,
            372 => YoloClassesOIV7::Pasta,
            373 => YoloClassesOIV7::Pastry,
            374 => YoloClassesOIV7::Peach,
            375 => YoloClassesOIV7::Pear,
            376 => YoloClassesOIV7::Pen,
            377 => YoloClassesOIV7::PencilCase,
            378 => YoloClassesOIV7::PencilSharpener,
            379 => YoloClassesOIV7::Penguin,
            380 => YoloClassesOIV7::Perfume,
            381 => YoloClassesOIV7::Person,
            382 => YoloClassesOIV7::PersonalCare,
            383 => YoloClassesOIV7::PersonalFlotationDevice,
            384 => YoloClassesOIV7::Piano,
            385 => YoloClassesOIV7::PicnicBasket,
            386 => YoloClassesOIV7::PictureFrame,
            387 => YoloClassesOIV7::Pig,
            388 => YoloClassesOIV7::Pillow,
            389 => YoloClassesOIV7::Pineapple,
            390 => YoloClassesOIV7::Pitcher, // (Container)
            391 => YoloClassesOIV7::Pizza,
            392 => YoloClassesOIV7::PizzaCutter,
            393 => YoloClassesOIV7::Plant,
            394 => YoloClassesOIV7::PlasticBag,
            395 => YoloClassesOIV7::Plate,
            396 => YoloClassesOIV7::Platter,
            397 => YoloClassesOIV7::PlumbingFixture,
            398 => YoloClassesOIV7::PolarBear,
            399 => YoloClassesOIV7::Pomegranate,
            400 => YoloClassesOIV7::Popcorn,
            401 => YoloClassesOIV7::Porch,
            402 => YoloClassesOIV7::Porcupine,
            403 => YoloClassesOIV7::Poster,
            404 => YoloClassesOIV7::Potato,
            405 => YoloClassesOIV7::PowerPlugsAndSockets,
            406 => YoloClassesOIV7::PressureCooker,
            407 => YoloClassesOIV7::Pretzel,
            408 => YoloClassesOIV7::Printer,
            409 => YoloClassesOIV7::Pumpkin,
            410 => YoloClassesOIV7::PunchingBag,
            411 => YoloClassesOIV7::Rabbit,
            412 => YoloClassesOIV7::Raccoon,
            413 => YoloClassesOIV7::Racket,
            414 => YoloClassesOIV7::Radish,
            415 => YoloClassesOIV7::Ratchet, // (Device)
            416 => YoloClassesOIV7::Raven,
            417 => YoloClassesOIV7::RaysAndSkates,
            418 => YoloClassesOIV7::RedPanda,
            419 => YoloClassesOIV7::Refrigerator,
            420 => YoloClassesOIV7::RemoteControl,
            421 => YoloClassesOIV7::Reptile,
            422 => YoloClassesOIV7::Rhinoceros,
            423 => YoloClassesOIV7::Rifle,
            424 => YoloClassesOIV7::RingBinder,
            425 => YoloClassesOIV7::Rocket,
            426 => YoloClassesOIV7::RollerSkates,
            427 => YoloClassesOIV7::Rose,
            428 => YoloClassesOIV7::RugbyBall,
            429 => YoloClassesOIV7::Ruler,
            430 => YoloClassesOIV7::Salad,
            431 => YoloClassesOIV7::SaltAndPepperShakers,
            432 => YoloClassesOIV7::Sandal,
            433 => YoloClassesOIV7::Sandwich,
            434 => YoloClassesOIV7::Saucer,
            435 => YoloClassesOIV7::Saxophone,
            436 => YoloClassesOIV7::Scale,
            437 => YoloClassesOIV7::Scarf,
            438 => YoloClassesOIV7::Scissors,
            439 => YoloClassesOIV7::Scoreboard,
            440 => YoloClassesOIV7::Scorpion,
            441 => YoloClassesOIV7::Screwdriver,
            442 => YoloClassesOIV7::Sculpture,
            443 => YoloClassesOIV7::SeaLion,
            444 => YoloClassesOIV7::SeaTurtle,
            445 => YoloClassesOIV7::Seafood,
            446 => YoloClassesOIV7::Seahorse,
            447 => YoloClassesOIV7::SeatBelt,
            448 => YoloClassesOIV7::Segway,
            449 => YoloClassesOIV7::ServingTray,
            450 => YoloClassesOIV7::SewingMachine,
            451 => YoloClassesOIV7::Shark,
            452 => YoloClassesOIV7::Sheep,
            453 => YoloClassesOIV7::Shelf,
            454 => YoloClassesOIV7::Shellfish,
            455 => YoloClassesOIV7::Shirt,
            456 => YoloClassesOIV7::Shorts,
            457 => YoloClassesOIV7::Shotgun,
            458 => YoloClassesOIV7::Shower,
            459 => YoloClassesOIV7::Shrimp,
            460 => YoloClassesOIV7::Sink,
            461 => YoloClassesOIV7::Skateboard,
            462 => YoloClassesOIV7::Ski,
            463 => YoloClassesOIV7::Skirt,
            464 => YoloClassesOIV7::Skull,
            465 => YoloClassesOIV7::Skunk,
            466 => YoloClassesOIV7::Skyscraper,
            467 => YoloClassesOIV7::SlowCooker,
            468 => YoloClassesOIV7::Snack,
            469 => YoloClassesOIV7::Snail,
            470 => YoloClassesOIV7::Snake,
            471 => YoloClassesOIV7::Snowboard,
            472 => YoloClassesOIV7::Snowman,
            473 => YoloClassesOIV7::Snowmobile,
            474 => YoloClassesOIV7::Snowplow,
            475 => YoloClassesOIV7::SoapDispenser,
            476 => YoloClassesOIV7::Sock,
            477 => YoloClassesOIV7::SofaBed,
            478 => YoloClassesOIV7::Sombrero,
            479 => YoloClassesOIV7::Sparrow,
            480 => YoloClassesOIV7::Spatula,
            481 => YoloClassesOIV7::SpiceRack,
            482 => YoloClassesOIV7::Spider,
            483 => YoloClassesOIV7::Spoon,
            484 => YoloClassesOIV7::SportsEquipment,
            485 => YoloClassesOIV7::SportsUniform,
            486 => YoloClassesOIV7::Squash, //(Plant)
            487 => YoloClassesOIV7::Squid,
            488 => YoloClassesOIV7::Squirrel,
            489 => YoloClassesOIV7::Stairs,
            490 => YoloClassesOIV7::Stapler,
            491 => YoloClassesOIV7::Starfish,
            492 => YoloClassesOIV7::StationaryBicycle,
            493 => YoloClassesOIV7::Stethoscope,
            494 => YoloClassesOIV7::Stool,
            495 => YoloClassesOIV7::StopSign,
            496 => YoloClassesOIV7::Strawberry,
            497 => YoloClassesOIV7::StreetLight,
            498 => YoloClassesOIV7::Stretcher,
            499 => YoloClassesOIV7::StudioCouch,
            500 => YoloClassesOIV7::Submarine,
            501 => YoloClassesOIV7::SubmarineSandwich,
            502 => YoloClassesOIV7::Suit,
            503 => YoloClassesOIV7::Suitcase,
            504 => YoloClassesOIV7::SunHat,
            505 => YoloClassesOIV7::Sunglasses,
            506 => YoloClassesOIV7::Surfboard,
            507 => YoloClassesOIV7::Sushi,
            508 => YoloClassesOIV7::Swan,
            509 => YoloClassesOIV7::SwimCap,
            510 => YoloClassesOIV7::SwimmingPool,
            511 => YoloClassesOIV7::Swimwear,
            512 => YoloClassesOIV7::Sword,
            513 => YoloClassesOIV7::Syringe,
            514 => YoloClassesOIV7::Table,
            515 => YoloClassesOIV7::TableTennisRacket,
            516 => YoloClassesOIV7::TabletComputer,
            517 => YoloClassesOIV7::Tableware,
            518 => YoloClassesOIV7::Taco,
            519 => YoloClassesOIV7::Tank,
            520 => YoloClassesOIV7::Tap,
            521 => YoloClassesOIV7::Tart,
            522 => YoloClassesOIV7::Taxi,
            523 => YoloClassesOIV7::Tea,
            524 => YoloClassesOIV7::Teapot,
            525 => YoloClassesOIV7::TeddyBear,
            526 => YoloClassesOIV7::Telephone,
            527 => YoloClassesOIV7::Television,
            528 => YoloClassesOIV7::TennisBall,
            529 => YoloClassesOIV7::TennisRacket,
            530 => YoloClassesOIV7::Tent,
            531 => YoloClassesOIV7::Tiara,
            532 => YoloClassesOIV7::Tick,
            533 => YoloClassesOIV7::Tie,
            534 => YoloClassesOIV7::Tiger,
            535 => YoloClassesOIV7::TinCan,
            536 => YoloClassesOIV7::Tire,
            537 => YoloClassesOIV7::Toaster,
            538 => YoloClassesOIV7::Toilet,
            539 => YoloClassesOIV7::ToiletPaper,
            540 => YoloClassesOIV7::Tomato,
            541 => YoloClassesOIV7::Tool,
            542 => YoloClassesOIV7::Toothbrush,
            543 => YoloClassesOIV7::Torch,
            544 => YoloClassesOIV7::Tortoise,
            545 => YoloClassesOIV7::Towel,
            546 => YoloClassesOIV7::Tower,
            547 => YoloClassesOIV7::Toy,
            548 => YoloClassesOIV7::TrafficLight,
            549 => YoloClassesOIV7::TrafficSign,
            550 => YoloClassesOIV7::Train,
            551 => YoloClassesOIV7::TrainingBench,
            552 => YoloClassesOIV7::Treadmill,
            553 => YoloClassesOIV7::Tree,
            554 => YoloClassesOIV7::TreeHouse,
            555 => YoloClassesOIV7::Tripod,
            556 => YoloClassesOIV7::Trombone,
            557 => YoloClassesOIV7::Trousers,
            558 => YoloClassesOIV7::Truck,
            559 => YoloClassesOIV7::Trumpet,
            560 => YoloClassesOIV7::Turkey,
            561 => YoloClassesOIV7::Turtle,
            562 => YoloClassesOIV7::Umbrella,
            563 => YoloClassesOIV7::Unicycle,
            564 => YoloClassesOIV7::Van,
            565 => YoloClassesOIV7::Vase,
            566 => YoloClassesOIV7::Vegetable,
            567 => YoloClassesOIV7::Vehicle,
            568 => YoloClassesOIV7::VehicleRegistrationPlate,
            569 => YoloClassesOIV7::Violin,
            570 => YoloClassesOIV7::Volleyball, // (Ball)
            571 => YoloClassesOIV7::Waffle,
            572 => YoloClassesOIV7::WaffleIron,
            573 => YoloClassesOIV7::WallClock,
            574 => YoloClassesOIV7::Wardrobe,
            575 => YoloClassesOIV7::WashingMachine,
            576 => YoloClassesOIV7::WasteContainer,
            577 => YoloClassesOIV7::Watch,
            578 => YoloClassesOIV7::Watercraft,
            579 => YoloClassesOIV7::Watermelon,
            580 => YoloClassesOIV7::Weapon,
            581 => YoloClassesOIV7::Whale,
            582 => YoloClassesOIV7::Wheel,
            583 => YoloClassesOIV7::Wheelchair,
            584 => YoloClassesOIV7::Whisk,
            585 => YoloClassesOIV7::Whiteboard,
            586 => YoloClassesOIV7::Willow,
            587 => YoloClassesOIV7::Window,
            588 => YoloClassesOIV7::WindowBlind,
            589 => YoloClassesOIV7::Wine,
            590 => YoloClassesOIV7::WineGlass,
            591 => YoloClassesOIV7::WineRack,
            592 => YoloClassesOIV7::WinterMelon,
            593 => YoloClassesOIV7::Wok,
            594 => YoloClassesOIV7::Woman,
            595 => YoloClassesOIV7::WoodBurningStove,
            596 => YoloClassesOIV7::Woodpecker,
            597 => YoloClassesOIV7::Worm,
            598 => YoloClassesOIV7::Wrench,
            599 => YoloClassesOIV7::Zebra,
            600 => YoloClassesOIV7::Zucchini,
            _ => panic!("The Label returned a bigger number than what was expected"),
        }
    }
}
