[package]
name = "yolov8-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
image = "0.25"

[build-dependencies]
cxx-build = "1.0"